#all time formats are in seconds
default time per round: 60
default time between round: 10
default amount of rounds: 3
# 1 to 20. each number is half a heart
snowball damage: 5
# each number increases by 1/20th of a second
snowball delay: 30
clear player inventory on game end: false
#Make players unable to roam the arena before games and between rounds
restrict movement: true
max players per team: 5

# this command will be ran by every player once the game ends. Use this to warp the player somewhere for example. Do NOT include the /
command after game: spawn
command after death: warp sbf