name: 'SnowBallFight'
version: 0.2
main: com.github.kevindagame.SnowBallFight
api-version: 1.16
author: KevinDaGame
description:  Custom snowball fight plugin
permissions:
  sbf.admin:
    default: op

depend: [WorldGuard]
commands:
  snowballfight:
    description: Main comand
    permission: sbf.admin
    aliases:
      - sbf

